rules:
  - pattern: "jmxpg.mbeans<type=AppInfo, Version=([^:]+)><>Status: ([^:]+)"
    name: "msee_jmxpg_mbeans_app_info_status"
    value: 1
    labels:
      version: $1
      status: $2

  - pattern: "jmxpg.mbeans<type=Requests, verb=([^:]+)><>([^:]+)"
    name: "msee_jmxpg_mbeans_requests_$2"
    labels:
      verb: $1
